# version: "2"


# networks:
#   bridge:
#     # name: bridge
#     # driver: bridge
#     external: true
#     labels:
#       com.docker.compose.internal.network: true
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
        - subnet: "2001:3984:3989::/64"
# extra_hosts:
#   - host.docker.internal:host-gateway
#   - payment.local:host-gateway
#   - syxpay-api.local:host-gateway
#   - notification.local:host-gateway

services:
  # utils:
  #   extra_hosts:
  #     - "example1:10.10.10.2"
  #     - "example2:10.10.10.3"
  web:
    networks:
      app_net:
        aliases:
          - payment.local
          - syxpay-api.local
          - notification.local
          - .local
    build: 
      dockerfile: ./Dockerfile-nginx
    depends_on:
      - php-fpm
      - mysql
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html
      - type: bind
        source: ./conf.d/
        target: /etc/nginx/conf.d/
    restart: on-failure
    # extra_hosts: # for linux hosts since version 20.10
    #   - host.docker.internal:host-gateway
    links:
        - php-fpm
  php-fpm:
    restart: on-failure
    networks:
      - app_net
    # extra_hosts: # for linux hosts since version 20.10
    #   - host.docker.internal:host-gateway
    #   - payment.local:host-gateway
    #   - syxpay-api.local:host-gateway
    #   - notification.local:host-gateway
    build: 
      dockerfile: ./Dockerfile-phpfpm
    volumes:
      - ./www:/var/www/html
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app_net
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql: